name: Test tap-pushbullet

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      NOXSESSION: ${{ matrix.session }}-${{ matrix.python-version }}
      PIP_CONSTRAINT: .github/workflows/constraints.txt
      FORCE_COLOR: "1"
    strategy:
      matrix:
        include:
        - {python-version: "3.11", session: "pytest"}
        - {python-version: "3.10", session: "pytest"}
        - {python-version: "3.9", session: "pytest"}
        - {python-version: "3.8", session: "pytest"}
        - {python-version: "3.7", session: "pytest"}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.5.0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4.5.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: |
        pip install pip
        pip --version

    - name: Install Poetry
      run: |
        pipx install poetry
        poetry --version

    - name: Install Nox
      run: |
        pipx install nox
        pipx inject nox nox-poetry
        nox --version

    - name: Run Nox
      env:
        TAP_PUSHBULLET_API_KEY: ${{ secrets.TAP_PUSHBULLET_API_KEY }}
      run: |
        nox
